### ISSUE TITLE
when multiple episodes air on the same day, events are sorted alphabetically not by episode num

### ISSUE THREAD

**Issue by nickysemenza** [kedarv/tv2cal#22]
google and apple calendar both appear to sort events by name, this means that the ordering is not chronological:
![image](https://github.com/kedarv/tv2cal/assets/707582/5620e77a-98a0-4a26-b7c7-2cc190ddb5e1)

![image](https://github.com/kedarv/tv2cal/assets/707582/b893c22c-a61a-4a2f-894d-9e50810b469f)

It would be nice if either the calendar events can have a sort key (no idea if its possible) or there was the episode number between the show name and episode name (when there's more than episode of the same show on a day)

**Comment by kedarv** [comment]
I think https://github.com/kedarv/tv2cal/pull/24/files should do the trick, will take ~24hrs upon deployment for clients to pull in new data though
